static const char *add_image_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 144 2 ",
"   c #434B53",
".  c #444B53",
"X  c #434A54",
"o  c #434B54",
"O  c #444A54",
"+  c #444B54",
"@  c #454C54",
"#  c #454C55",
"$  c #464C56",
"%  c #464D56",
"&  c #474E57",
"*  c #484E57",
"=  c #484F57",
"-  c #494F58",
";  c #495058",
":  c #495059",
">  c #4B525A",
",  c #4C535B",
"<  c #4D535B",
"1  c #4D535C",
"2  c #4E545C",
"3  c #4F555D",
"4  c #50565E",
"5  c #51575F",
"6  c #52585F",
"7  c #525860",
"8  c #535961",
"9  c #545A62",
"0  c #585D64",
"q  c #5F646B",
"w  c #63676D",
"e  c #64696F",
"r  c #656A70",
"t  c #6B6F74",
"y  c #6B6F76",
"u  c #6C6F75",
"i  c #6C7075",
"p  c #6D7177",
"a  c #73767C",
"s  c #73777C",
"d  c #74787E",
"f  c #777B80",
"g  c #797D82",
"h  c #7C7F84",
"j  c #7D8085",
"k  c #7D8186",
"l  c #83868A",
"z  c #85898E",
"x  c #87898E",
"c  c #8A8D91",
"v  c #8B8E93",
"b  c #8D9094",
"n  c #8F9296",
"m  c #909296",
"M  c #929599",
"N  c #A8AAAD",
"B  c #AAADB0",
"V  c #ABADB1",
"C  c #ACAEB1",
"Z  c #ADAEB1",
"A  c #AFB2B5",
"S  c #B0B2B5",
"D  c #B3B4B6",
"F  c #B8BABC",
"G  c #B8BABD",
"H  c #B8BBBD",
"J  c #B9BBBD",
"K  c #BDBEC0",
"L  c #BCBEC1",
"P  c #BDBFC1",
"I  c #BFC0C2",
"U  c #BEC0C3",
"Y  c #C0C1C3",
"T  c #C1C2C4",
"R  c #C2C3C5",
"E  c #C5C7C9",
"W  c #CBCCCE",
"Q  c #CCCDD0",
"!  c #D1D3D4",
"~  c #D2D3D4",
"^  c #D3D4D6",
"/  c #DADBDC",
"(  c #DCDEDF",
")  c #DEDFDF",
"_  c #E0E0E1",
"`  c #E5E5E6",
"'  c #E7E7E8",
"]  c #E9EAEB",
"[  c #ECECED",
"{  c #ECEDED",
"}  c #EDEEEE",
"|  c #EEEEEF",
" . c #E9EEF4",
".. c #EAEEF4",
"X. c #EAEFF5",
"o. c #EBEFF5",
"O. c #EBF0F5",
"+. c #ECF0F5",
"@. c #ECF0F6",
"#. c #ECF1F6",
"$. c #EEF2F6",
"%. c #EEF2F7",
"&. c #EFF3F7",
"*. c #F1F1F2",
"=. c #F0F3F7",
"-. c #F4F5F5",
";. c gray96",
":. c #F6F6F6",
">. c #F6F6F7",
",. c #F6F7F7",
"<. c gray97",
"1. c #F1F4F8",
"2. c #F1F5F8",
"3. c #F2F5F8",
"4. c #F4F7FA",
"5. c #F5F7FA",
"6. c #F6F8FA",
"7. c #F7F8FA",
"8. c #F6F8FB",
"9. c #F7F8FB",
"0. c #F7F9FB",
"q. c #F8F8F8",
"w. c #F9F9FA",
"e. c #F8F9FB",
"r. c gray98",
"t. c #F8FAFC",
"y. c #F9FAFC",
"u. c #F9FBFC",
"i. c #FAFBFC",
"p. c #FAFBFD",
"a. c #FAFCFC",
"s. c #FBFCFD",
"d. c gray99",
"f. c #FCFCFD",
"g. c #FCFDFD",
"h. c #FDFDFD",
"j. c #FCFDFE",
"k. c #FDFDFE",
"l. c #FDFEFE",
"z. c #FEFEFE",
"x. c #FEFEFF",
"c. c #FEFFFF",
"v. c gray100",
"b. c None",
/* pixels */
"b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.b.    + + + + + + + + + +   @ + + + + + + + +   @ b.b.b.b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.@ @ @ + + + + + + + + + + + @ + + + + + + + + + + +   o b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.@ = d Z T T T R T I R T T T R T T T T R T R D y > d g 5 @ o b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ @ h / r.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.[ z 5 S ' L p @   b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 2 B k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.[ z 7 H k.r.~ d @ @ b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 6 H k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.[ v 1 S k.k.r.R 0 @ b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.q.N = v ] d.k.} z @ + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.k.k.k.k.i.s.s.s.s.s.s.r.s.s.k.k.~ e 2 m W _ ) m = + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.q.O. . . . . . . . .O.q.k.q.J q = 2 2 2 = @ + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.r.#.O.O.#.#.O.O.O.O.#.i.k.k.>.! M d i i t e & b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.q.>.>.>.>.*.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.>.E b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.Q r @ b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 @ b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 @ b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.R 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.I 7 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.o 7 H k.k.k.k.k.k.k.k.s.k.k.k.s.k.k.k.k.s.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.@ 7 J k.k.k.k.k.#.#.#.O.O.O.O.O.O.O.O.O.O.#.#.O.#.#.s.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.@ 7 J k.k.k.k.i.#. . . . . . . .X. . . . . . . . .#.i.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.@ 7 J k.k.k.k.k.k.s.r.s.i.s.t.s.q.q.s.s.t.i.i.s.r.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.i.i.q.t.9.i.q.q.t.i.t.9.i.t.t.i.q.i.k.k.k.k.k.R 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.s.#.@. .@. .@. .O.O. .O. . . . .@. .#.s.k.k.k.k.I 7 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.s.4.%.%.%.%.&.#.&.#.#.&.#.&.%.%.%.%.4.s.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.s.k.k.s.k.k.k.k.k.k.k.k.s.k.k.s.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.4.&.&.&.&.&.&.&.&.&.&.&.t.k.k.k.q.4.s.k.k.k.k.R 9 @ b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.r.#. . . . . . . . . . . .&.k.k.k.4. .q.k.k.k.k.I 7 @ b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.q.q.4.t.q.4.q.4.q.4.q.t.t.k.k.k.k.t.k.k.k.k.k.U 9 o b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 H k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.U 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.R 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.I 7 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 7 J k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.L 9 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ 1 C k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.i.C 1 + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.+ @ l ` k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.d./ k + + b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.# > b L R R R R R R R R R R R R R R R R R R R R R R R R D k - + b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.+ + & > @ > @ = = = = = = = - > @ > @ - = = = > @ > @ @ + + b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.b.o + @ @ + @ + + + + + + + + @ @ + @ + + + + @ @ + + + b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.",
"b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b."
};


static const char *image_icon_1[] = {
/* columns rows colors chars-per-pixel */
"64 64 97 2 ",
"   c #434A53",
".  c #434B53",
"X  c #444A53",
"o  c #444B53",
"O  c #434B54",
"+  c #444A54",
"@  c #444B54",
"#  c #454C55",
"$  c #4A5159",
"%  c #4B515A",
"&  c #4B525B",
"*  c #545B63",
"=  c #595E67",
"-  c #5A6068",
";  c #60666D",
":  c #61676E",
">  c #61676F",
",  c #62686F",
"<  c #636970",
"1  c #646971",
"2  c #646A72",
"3  c #70757C",
"4  c #757A81",
"5  c #70C1FE",
"6  c #71C1FE",
"7  c #70C2FE",
"8  c #71C2FE",
"9  c #70C2FF",
"0  c #71C2FF",
"q  c #73C3FF",
"w  c #74C3FF",
"e  c #75C4FF",
"r  c #7AC6FF",
"t  c #7BC6FF",
"y  c #7CC7FF",
"u  c #A8ACB0",
"i  c #ABAEB2",
"p  c #B0B3B7",
"a  c #B4B7BB",
"s  c #BCBEC1",
"d  c #84CAFF",
"f  c #88CCFF",
"g  c #8ACDFF",
"h  c #95D2FF",
"j  c #96D2FF",
"k  c #9BD4FF",
"l  c #9CD4FF",
"z  c #A5D8FE",
"x  c #A9DAFE",
"c  c #B2DEFF",
"v  c #B3DEFF",
"b  c #B8E0FF",
"n  c #B8E1FF",
"m  c #BFE3FF",
"M  c #C2C4C7",
"N  c #CBCDCF",
"B  c #CCCED0",
"V  c #CCCED1",
"C  c #CDCFD1",
"Z  c #CED0D2",
"A  c #CFD0D3",
"S  c #CFD1D3",
"D  c #D0D2D4",
"F  c #D1D3D5",
"G  c #D2D3D5",
"H  c #D2D4D6",
"J  c #DADCDE",
"K  c #DFE1E2",
"L  c #C0E4FF",
"P  c #C7E7FF",
"I  c #C8E7FF",
"U  c #D4EDFF",
"Y  c #DBF0FF",
"T  c #DEF1FF",
"R  c #E4E4E6",
"E  c #ECEDEE",
"W  c #EDEDEE",
"Q  c #EDEEEF",
"!  c #EEEFF0",
"~  c #EFEFF0",
"^  c #E0F2FF",
"/  c #E1F2FF",
"(  c #E2F3FF",
")  c #E8F5FF",
"_  c #EAF6FF",
"`  c #EDF7FF",
"'  c #EEF8FF",
"]  c #F0F0F1",
"[  c #F1F9FF",
"{  c #F4FAFF",
"}  c #FBFBFB",
"|  c #FCFEFF",
" . c #FDFEFF",
".. c #FEFEFE",
"X. c #FEFFFF",
"o. c white",
"O. c None",
/* pixels */
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.0 0 0 0 l v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v k 0 9 0 0 O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.0 0 t ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.( t 0 0 O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 I o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.P 0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 [ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[ 0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.) ` o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.m t 0 0 g Y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.v 9 9 0 0 0 e T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.{ e 0 0 0 0 0 0 j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.U 0 0 0 0 0 0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.U 0 0 0 0 0 0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.{ e 0 0 0 0 0 0 j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.n 0 0 0 0 0 w ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.L t 0 0 g T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.| ) ' o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.} H M R o.o.o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.F - @ @ @ 4 Q o.o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.N $ @ @ @ @ # - E o.o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.B $ @ @ @ @ # # + ; E o.o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.B $ @ @ @ @ @ @ @ @ @ , ! o.o.o.o.o.0 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 0 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.B & @ @ @ @ @ @ @ @ @ @ @ , ! o.o.o.o.d 0 0 O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.0 0 d o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.B & @ @ @ @ @ @ @ @ @ @ @ @ @ , Q o.o.o.) x O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.z ) o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.B & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 2 Q o.o.o.o.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.Z & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o 2 Q o.o.o.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.o.o.o.F p s ] o.o.o.o.o.o.o.o.o.o.o.S & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o @ 2 ] o.o.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.o.Q 3 @ @ @ $ a o.o.o.o.o.o.o.o.o.Z & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o 2 ] o.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.Q ;   @ @ @ # @ i o.o.o.o.o.o.o.F & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o 2 R O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.J ; #   #   @ @ @ @ i o.o.o.o.o.F $ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ = O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.*     #   # @ @ @ @ @ i o.o.o.F & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.+ O # #   #   @ @ @ @ @ @ i o.S & @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.o #     #   # @ @ @ @ @ @   * # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.  #   #   #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.#   #   #   # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.# #   #   #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.    #   #   # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.# #   #   #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.    #   #   # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.. #   #   #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.o   #   #   # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.  # #   #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @   O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.    #   # @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ o O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.  # #   @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @   + O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O."
};

static const char *image_icon_2[] = {
/* columns rows colors chars-per-pixel */
"64 64 146 2 ",
"   c #434A53",
".  c #434B53",
"X  c #444A53",
"o  c #444B53",
"O  c #434A54",
"+  c #434B54",
"@  c #444A54",
"#  c #444B54",
"$  c #464D56",
"%  c #474E57",
"&  c #495059",
"*  c #4E545D",
"=  c #4F565E",
"-  c #50575F",
";  c #515860",
":  c #545B63",
">  c #585E66",
",  c #595F67",
"<  c #5C626A",
"1  c #5E646B",
"2  c #6B7078",
"3  c #6D737A",
"4  c #6F747B",
"5  c #747A80",
"6  c #7B8086",
"7  c #7D8288",
"8  c #70C1FE",
"9  c #71C1FE",
"0  c #70C2FE",
"q  c #71C2FF",
"w  c #72C2FF",
"e  c #73C3FF",
"r  c #74C3FF",
"t  c #77C4FF",
"y  c #78C5FF",
"u  c #79C6FF",
"i  c #7AC6FE",
"p  c #7AC6FF",
"a  c #7BC6FF",
"s  c #7DC7FF",
"d  c #7EC8FF",
"f  c #7FC8FF",
"g  c #898D93",
"h  c #8D9398",
"j  c #9A9EA2",
"k  c #9B9FA4",
"l  c #9CA0A4",
"z  c #A0A3A8",
"x  c #A3A7AB",
"c  c #A6A9AD",
"v  c #A7AAAF",
"b  c #B4B7BB",
"n  c #B6B8BC",
"m  c #B7BABD",
"M  c #81C9FF",
"N  c #83CAFF",
"B  c #84CAFF",
"V  c #85CBFF",
"C  c #86CBFF",
"Z  c #87CCFF",
"A  c #8ACDFF",
"S  c #8DCEFF",
"D  c #8ECEFF",
"F  c #90CFFF",
"G  c #92D0FF",
"H  c #96D2FF",
"J  c #9BD4FF",
"K  c #9CD5FF",
"L  c #9ED5FF",
"P  c #A1D6FE",
"I  c #A0D6FF",
"U  c #A3D7FF",
"Y  c #A3D8FF",
"T  c #A4D8FF",
"R  c #A5D8FF",
"E  c #A7D9FF",
"W  c #A8D9FF",
"Q  c #A8DAFF",
"!  c #A9DAFF",
"~  c #AADAFF",
"^  c #AADBFF",
"/  c #ABDBFF",
"(  c #ADDCFF",
")  c #AFDDFF",
"_  c #B1DEFF",
"`  c #B8E0FF",
"'  c #B9E1FF",
"]  c #BCE2FF",
"[  c #BDE3FF",
"{  c #BEE3FF",
"}  c #BFE3FF",
"|  c #C5C7CA",
" . c #D7D8DA",
".. c #D7D9DB",
"X. c #D8DADB",
"o. c #DDDEDF",
"O. c #C0E4FF",
"+. c #C1E4FF",
"@. c #C2E5FF",
"#. c #C5E6FF",
"$. c #CAE8FF",
"%. c #CCE9FF",
"&. c #CDEAFF",
"*. c #CEEAFF",
"=. c #CFEAFF",
"-. c #D0EBFF",
";. c #D3ECFF",
":. c #D4ECFF",
">. c #D4EDFF",
",. c #D5EDFF",
"<. c #D6EEFF",
"1. c #D8EEFF",
"2. c #DAEFFF",
"3. c #DCF0FF",
"4. c #DDF0FF",
"5. c #E2E3E4",
"6. c #E2E3E5",
"7. c #E4E5E6",
"8. c #E7E8E9",
"9. c #ECEDEE",
"0. c #EDEDEE",
"q. c #E0F2FF",
"w. c #E1F2FF",
"e. c #E3F3FE",
"r. c #E5F4FF",
"t. c #E6F4FF",
"y. c #E8F5FF",
"u. c #EBF6FF",
"i. c #ECF7FF",
"p. c #EDF7FF",
"a. c #EFF8FF",
"s. c #F6F7F7",
"d. c #F1F9FF",
"f. c #F2F9FF",
"g. c #F6FBFF",
"h. c #F7FBFF",
"j. c #F8FCFF",
"k. c #F9FCFF",
"l. c #F9FDFF",
"z. c #FAFDFF",
"x. c #FBFDFF",
"c. c #FCFEFF",
"v. c #FDFEFF",
"b. c #FEFFFF",
"n. c white",
"m. c None",
/* pixels */
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.. . # # # # # # # # # # # # # # # # # # # # # # # # # # # . + # m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.+ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # o . m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.o # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # # ; m 0.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # g b 3 # # # . m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # % X.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # k n.n.| : # # o m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # 7 n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # l n.n.n.8.> # # + m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # j n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # j n.n.n.n.o.& # # m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.m # # 5 n.n.n.n.n.k # # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.5.# # %  .n.n.n.n.0.% # o m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.5 + # ; n 9.n.n.n.4 # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.5.= # + # # # # # # # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n. .> . o # # # # # # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.s.v 2 * # # # # # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.l.:.O.O.:.l.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.} p q q q q p } n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.U 0 q q q q q q q Y n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.} q q q B / ! M q q q } n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.l.t q q ! n.n.n.l.! q q p l.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.:.q q B l.n.n.n.n.l.B q q :.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.O.q q / n.n.n.n.n.n.! q q O.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.O.q q R n.n.n.n.n.n.! q q O.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.:.q q B l.n.n.n.n.n.M q q :.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.l.p q q ! l.n.n.l.R q q p l.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.O.q q q B ! ! B q q q O.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.U q q q q q q q q R n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.} p q q q q p O.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.l.:.O.O.:.l.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v + # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.n.;.;.n.n.n.n.n.n.n.n.&.&.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.n.} q 0 ! n.n.n.n.n.n.' q q ' n.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.n.&.q q q q } n.n.n.n.2.q q q q :.n.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # l n.n.n.n.n.n.n.n.n.q.q q q q q e :.n.n.n.Z q q q q p a.n.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.# # x n.n.n.n.n.n.n.n.p.s q q F F q q t q.n.n.B q d d q q S l.n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.o 1 7.n.n.n.n.n.n.n.g.B q q M d.d.M q q M d.n.a.} u.3.t q q ! n.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.n.n.n.l.H q q p t.n.n.t.p q q A g.n.n.n.n.} q q q $.n.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.n.n.n.Y q q t :.n.n.n.n.2.q q q J n.n.n.n.n.L q q p r.n.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.n.n.} q q q O.n.n.n.n.n.n.O.q q q ! n.n.n.n.l.B q q Z h.n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.n.$.q q q _ n.n.n.n.n.n.n.n._ q q q O.n.n.n.n.u.t q q L n.n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.q.t q q J n.n.n.n.n.n.n.n.n.n.L q q q :.n.n.n.n.&.q q q } n.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.n.u.s q q S l.n.n.n.n.n.n.n.n.n.n.l.S q q t q.n.n.n.n._ q q q 3.n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.g.M q q M a.n.n.n.n.n.n.n.n.n.n.n.n.d.M q q M a.n.n.n.n.F q q B n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.n.H q q p t.n.n.n.n.n.n.n.n.n.n.n.n.n.n.t.p q q A g.n.n.n.d.d q M n.n.n.n.n.v # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.n.R q q q :.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.:.q q q J n.n.n.n.p.O.p.n.n.n.n.n.z # # . m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.n.' q q q #.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.#.q q q ! n.n.n.n.n.n.n.n.n.n.n.6 # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.&.q q q ( n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.( q q q O.n.n.n.n.n.n.n.n.n. .% # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.t q q J n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.J q q q ;.n.n.n.n.n.n.0.b = # # # m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.q q q A j.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.l.A q q t t.n.n.n.5.< + # # # o m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.q q p q.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.q.p q q U n.n.n.h # # # # # m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.q q m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.q q m.m.m.m.m.o # # m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.",
"m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m."
};



static const char *color_image_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 235 2 ",
"   c #434B53",
".  c #444A53",
"X  c #434A54",
"o  c #434B54",
"O  c #444A54",
"+  c #444B54",
"@  c #454C55",
"#  c #464D55",
"$  c #464D56",
"%  c #484E57",
"&  c #484F57",
"*  c #495058",
"=  c #495059",
"-  c #4C535B",
";  c #4D535B",
":  c #4E545C",
">  c #4F555D",
",  c #51575F",
"<  c #52585F",
"1  c #525860",
"2  c #535961",
"3  c #545A62",
"4  c #585E65",
"5  c #5A5F66",
"6  c #5C6268",
"7  c #5F646B",
"8  c #656A70",
"9  c #6B6F74",
"0  c #6B6F76",
"q  c #6B7076",
"w  c #6C7075",
"e  c #6E7378",
"r  c #73777C",
"t  c #74797F",
"y  c #75797F",
"u  c #777B80",
"i  c #797E83",
"p  c #7B7E83",
"a  c #7C7F84",
"s  c #71C1FE",
"d  c #71C1FF",
"f  c #70C2FE",
"g  c #71C2FF",
"h  c #72C2FF",
"j  c #72C3FF",
"k  c #74C3FF",
"l  c #75C3FF",
"z  c #76C4FF",
"x  c #77C4FF",
"c  c #78C4FF",
"v  c #78C5FF",
"b  c #79C5FF",
"n  c #7AC5FF",
"m  c #7BC5FF",
"M  c #7BC6FF",
"N  c #7CC6FF",
"B  c #7EC6FF",
"V  c #7EC7FF",
"C  c #7FC7FF",
"Z  c #85898E",
"A  c #878A8E",
"S  c #8A8D91",
"D  c #8B8E93",
"F  c #8F9296",
"G  c #909396",
"H  c #929599",
"J  c #A8AAAD",
"K  c #AAADB0",
"L  c #ACAEB1",
"P  c #ADAEB1",
"I  c #AFB2B5",
"U  c #B0B2B5",
"Y  c #B3B4B6",
"T  c #B7B9BC",
"R  c #B8BABC",
"E  c #B8BABD",
"W  c #B8BBBD",
"Q  c #B9BBBD",
"!  c #BCBEC1",
"~  c #BFC0C2",
"^  c #BEC0C3",
"/  c #BFC0C3",
"(  c #80C7FF",
")  c #81C7FF",
"_  c #81C8FF",
"`  c #82C8FF",
"'  c #83C9FF",
"]  c #84C9FF",
"[  c #85C9FF",
"{  c #86C9FF",
"}  c #87C9FF",
"|  c #87CAFF",
" . c #8BCBFE",
".. c #8ACBFF",
"X. c #8ACCFF",
"o. c #8CCCFF",
"O. c #8DCCFF",
"+. c #8ECCFF",
"@. c #8FCDFF",
"#. c #90CDFF",
"$. c #92CEFF",
"%. c #92CFFF",
"&. c #94CEFF",
"*. c #94CFFF",
"=. c #95CFFF",
"-. c #96D0FF",
";. c #97D0FF",
":. c #98D0FF",
">. c #9AD1FF",
",. c #9ED2FF",
"<. c #9ED3FF",
"1. c #A4D5FF",
"2. c #A5D6FF",
"3. c #A8D7FF",
"4. c #A9D7FF",
"5. c #AAD7FF",
"6. c #A8D8FF",
"7. c #ACD8FF",
"8. c #ADD9FF",
"9. c #AEDAFF",
"0. c #AFDAFF",
"q. c #B0DAFF",
"w. c #B1DAFF",
"e. c #B2DBFF",
"r. c #B5DDFF",
"t. c #B6DDFF",
"y. c #B7DDFF",
"u. c #B8DEFF",
"i. c #B8DFFF",
"p. c #BADFFF",
"a. c #BBDFFF",
"s. c #BCDFFF",
"d. c #BEE0FF",
"f. c #BEE1FF",
"g. c #BFE1FF",
"h. c #C0C1C3",
"j. c #C0C2C4",
"k. c #C7C9CB",
"l. c #CBCCCE",
"z. c #CFD0D2",
"x. c #D1D3D4",
"c. c #D2D3D4",
"v. c #D5D6D7",
"b. c #D6D8D9",
"n. c #D9DADC",
"m. c #DADBDC",
"M. c #DEDFE0",
"N. c #C1E2FF",
"B. c #C2E2FF",
"V. c #C3E3FF",
"C. c #C5E4FF",
"Z. c #C6E4FF",
"A. c #C6E5FF",
"S. c #C8E5FF",
"D. c #CAE5FF",
"F. c #CAE6FF",
"G. c #CBE6FF",
"H. c #CDE7FF",
"J. c #CEE7FF",
"K. c #CEE8FF",
"L. c #CFE9FF",
"P. c #D1E8FF",
"I. c #D1E9FF",
"U. c #D3EAFF",
"Y. c #D4EAFF",
"T. c #D5EBFF",
"R. c #D6EBFF",
"E. c #D7EBFF",
"W. c #D5ECFF",
"Q. c #D6ECFF",
"!. c #D9EDFF",
"~. c #DCEEFF",
"^. c #DEEFFF",
"/. c #DFF0FF",
"(. c #E0E0E1",
"). c #E7E8E9",
"_. c #E9EAEB",
"`. c #ECECED",
"'. c #ECEDED",
"]. c #EDEEEE",
"[. c #EEEEEF",
"{. c #E0F0FF",
"}. c #E0F1FF",
"|. c #E1F1FF",
" X c #E2F1FF",
".X c #E3F1FF",
"XX c #E2F2FF",
"oX c #E3F2FF",
"OX c #E4F2FF",
"+X c #E5F2FF",
"@X c #E7F3FF",
"#X c #E7F4FF",
"$X c #E9F4FF",
"%X c #E9F5FF",
"&X c #EBF5FF",
"*X c #ECF5FF",
"=X c #ECF6FF",
"-X c #EDF6FF",
";X c #EDF7FF",
":X c #EFF7FF",
">X c #EFF8FF",
",X c #F1F1F2",
"<X c #F3F3F4",
"1X c gray96",
"2X c #F6F6F6",
"3X c #F6F6F7",
"4X c #F6F7F7",
"5X c gray97",
"6X c #F7F7F8",
"7X c AliceBlue",
"8X c #F1F8FF",
"9X c #F2F9FF",
"0X c #F4FAFF",
"qX c #F5FAFF",
"wX c #F6FBFF",
"eX c #F7FBFF",
"rX c #F8F8F8",
"tX c gray98",
"yX c #FBFCFC",
"uX c #F8FCFF",
"iX c #F9FCFF",
"pX c #FAFDFF",
"aX c #FBFDFF",
"sX c gray99",
"dX c #FCFCFD",
"fX c #FDFDFD",
"gX c #FDFDFE",
"hX c #FCFDFF",
"jX c #FCFEFF",
"kX c #FDFEFF",
"lX c #FEFEFE",
"zX c #FEFEFF",
"xX c #FEFFFF",
"cX c gray100",
"vX c None",
/* pixels */
"vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXvXvX    + + + + + + + + + + + . + + + + + + + +   o vXvXvXvXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXvX# . # + + + + + + + + + + + # + + + + + + + + + + + +   vXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvX. & y P j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.Y w * y i , # + vXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ # a m.rXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX`.A , U )./ e # . vXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ : K gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX`.A < W gXgXv.r . o vXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ < W gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX[.D : U gXgXrX^ 4   vXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 W gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXrXJ * S _.gXgX`.A # vXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 W gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXc.8 < F l.(.(.G & + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXrXQ 7 * : : : *   + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX<Xc.H y w 9 5 # + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXrX<X<X<XW 1 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 W gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXpXgXgXgXgXgXgXgXgX/ 1 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXOXC.i.C.oXpXgXgXgXgXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXwXf.[ z l l [ f.qXgXgXgXgXgX/ 1 # vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXV.N b ;.6.;.b b V.pXgXgXgXgX/ 3 o vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgX;XO.z t.9XpX9Xt.z O.;XgXgXgXgXj.3 # vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXW.N o.#XgXgXgXOXo.' W.gXgXgXgX/ 3 o vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 W gXgXgXgXgXgXgXgXgXgXgXgXgXI.N ;.;XgXgXgX>X%.b I.gXgXgXgX^ 3 o vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgX/.' N W.pXgXgXW.V ' oXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX# 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXpX1.k &.D.!.D.&.l 1.wXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX# 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXoX&.l b ' b l =.oXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXpXoXe.=.o.&.9.oXgXgXgXgXgXgX/ 1 # vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpX=XoX=XpXgXgXgXgXgXgXgX/ 3 o vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXj.3 o vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXgXgXgXgXgXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgXgX=XC.OXgXgXgXgXpXH.H.wXgXgXgXgXgXgXgXgXgX/ 1 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 Q gXgXgXgXgXgXgX#X<.z ;.#XgXgXpXD.' ' D.gXgXgXgXgXgXgXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 1 W gXgXgXgXgXgX;X3.b k l 1.;XgX=X+.k k ..^.gXgXgXgXgXgXgXgXj.3 # vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvX+ 6 k.gXgXgXgXgXwXt.z ..9.[ l e.9X;X,.,.&.l :.=XgXgXgXgXgXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXj.<XgXgXgXgXpXV.b ' D.wXD.N b s.qX;X;X^.O.z 3.9XgXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXgXgXgXgXpXD.' b V.wXgXqXV.b N C.pXgXpXH.' b V.pXgXgXgXgXgX^ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXgXgXgXgXW.o.z e.9XgXgXgX9Xe.z [ I.pXgXpXd.b [ W.gXgXgXgXgX/ 1 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXgXgXpXoX=.l 1.>XgXgXgXgXgX;X1.k &.^.gXgX>X6.k &.OXgXgXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXgXgX=X,.l :.OXgXgXgXgXgXgXgX=X;.l :.OXgXgX#X;.z 1.9XgXgXgXj.3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXgX9X3.z O.oXgXgXgXgXgXgXgXgXgX^.O.l 1.>XgXgXW.[ b I.gXgXgX/ 3 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXgXwXt.b [ I.pXgXgXgXgXgXgXgXgXgXgXI...z e.9XgXgXH.9.OXgXgXgX! 1 + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXqXV.N ( D.pXgXgXgXgXgXgXgXgXgXgXgXpXC.( b i.pXgXpXwXgXgXgXgXK ; + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXi.' b i.pXgXgXgXgXgXgXgXgXgXgXgXgXgXpXi.b N C.pXgXgXgXgXrXm.p # + vXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXl z 9.9XgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9X9.b [ Y.gXgX6Xz.P u % + vXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXk k o.oXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXoX..k :.>XgXb.w + + + vXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXf vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXs vXvXvXvX* + vXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvX",
"vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvX"
};

static const char *save_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 16 1 ",
"  c #263238",
". c #C62828",
"X c #CB2B2A",
"o c #E63C32",
"O c #F44336",
"+ c #C05355",
"@ c #E1655E",
"# c #B3ADB3",
"$ c #B8B0B5",
"% c #B0BEC5",
"& c #CFD8DC",
"* c #FCD3D0",
"= c #FCD4D0",
"- c #FCD4D1",
"; c gray100",
": c None",
/* pixels */
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::OOO......%%%%%%%%%%%%%%%%%%%OOO:::::::::::",
"::::::OOO......%%%%%%%%%%%%%%%%%%%OOOO::::::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOO:::::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOO::::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOO:::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOOO::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOOO::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOOO::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOOO::::::",
"::::::OOO......%%%%%%%%%%%    %%%%OOOOOOOO::::::",
"::::::OOOX.....#%%%%%%%%%%%%%%%%%$OOOOOOOO::::::",
"::::::OOOoX....+#%%%%%%%%%%%%%%%$@OOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOO-;;;;;;;;;;;;;;;;;;;;;;;;;;;;-OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;&&&&&&&&&&&&&&&&&&&&&&;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;OOO::::::",
"::::::OOO-;;;;;;;;;;;;;;;;;;;;;;;;;;;;*OOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::"
};

static const char *save_as_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 50 1 ",
"  c #263238",
". c #404C4C",
"X c #66674A",
"o c #7B7852",
"O c #C62828",
"+ c #CB2B2A",
"@ c #E63C32",
"# c #F44336",
"$ c #F54932",
"% c #C05355",
"& c #E1655E",
"* c #E47272",
"= c #E57272",
"- c #E57373",
"; c #E17777",
": c #E17778",
"> c #E27878",
", c #E27879",
"< c #FD870B",
"1 c #FF9800",
"2 c #FD9D0A",
"3 c #FF9F0C",
"4 c #CEA318",
"5 c #F6A52A",
"6 c #FFAC31",
"7 c #FFAC32",
"8 c #FFC107",
"9 c #F9C423",
"0 c #F6C32C",
"q c #FFC932",
"w c #AAA37A",
"e c #D0987A",
"r c #E8C66B",
"t c #E8C76B",
"y c #BDB388",
"u c #B3ADB3",
"i c #B8B0B5",
"p c #B2B8BE",
"a c #AFBDC4",
"s c #AFBEC4",
"d c #B0BEC5",
"f c #D5D6C3",
"g c #D2D4CC",
"h c #CFD8DC",
"j c #FCD4D0",
"k c #FCD4D1",
"l c #FFF8E2",
"z c #FFF8ED",
"x c gray100",
"c c None",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccc###OOOOOOddddddddddddddddd###cccccccccccccc",
"ccccc###OOOOOOddddddddddddddddd####ccccccccccccc",
"ccccc###OOOOOOddddddddd    dddd#####cccccccccccc",
"ccccc###OOOOOOddddddddd    dddd######ccccccccccc",
"ccccc###OOOOOOddddddddd    dddd#######cccccccccc",
"ccccc###OOOOOOddddddddd    dddd########ccccccccc",
"ccccc###OOOOOOddddddddd    dddd########ccccccccc",
"ccccc###OOOOOOddddddddd    dddd########ccccccccc",
"ccccc###OOOOOOddddddddd    dddd########ccccccccc",
"ccccc###+OOOOOudddddddddddddddi########ccccccccc",
"ccccc###@+OOOO%udddddddddddddi&########ccccccccc",
"ccccc##################################ccccccccc",
"ccccc##################################ccccccccc",
"ccccc##################################ccccccccc",
"ccccc##################################ccccccccc",
"ccccc##################################ccccccccc",
"ccccc###kxxxxxxxxxxxxxxxxxxxxxxxxxxj###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxxxxxxxxxxxx###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxxxxxxxxxxxx###ccccccccc",
"ccccc###xxxxhhhhhhhhhhhhXowfhhhhxxxx###ccccccccc",
"ccccc###xxxxhhhhhhhhhhhho.489tghxxxx###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxy488q37zxxxx###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxl88q3117zxxx###ccccccccc",
"ccccc###xxxxhhhhhhhhhhhhh90211117zxx###ccccccccc",
"ccccc###xxxxhhhhhhhhhhhhht21111117zx###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxz711111117z###ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxxz711111117$##ccccccccc",
"ccccc###xxxxhhhhhhhhhhhhhhhg51111111<$#ccccccccc",
"ccccc###xxxxhhhhhhhhhhhhhhhhg51111111<$ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxxxxxz71111111<ccccccccc",
"ccccc###xxxxxxxxxxxxxxxxxxxxxxz7111111eacccccccc",
"ccccc###jxxxxxxxxxxxxxxxxxxxxxxz71111eddaccccccc",
"ccccc###########################$<11edddp>cccccc",
"ccccc############################$<edddp;-=ccccc",
"cccccccccccccccccccccccccccccccccccaddp:--=ccccc",
"ccccccccccccccccccccccccccccccccccccap>--=cccccc",
"ccccccccccccccccccccccccccccccccccccc>---ccccccc",
"cccccccccccccccccccccccccccccccccccccc==cccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccc"
};
static const char *icon_xpm_data[] = {
/* columns rows colors chars-per-pixel */
"32 32 6 1",
"  c black",
". c navy",
"X c red",
"o c yellow",
"O c gray100",
"+ c None",
/* pixels */
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++              ++++++++++",
"++++++++ ............ ++++++++++",
"++++++++ ............ ++++++++++",
"++++++++ .OO......... ++++++++++",
"++++++++ .OO......... ++++++++++",
"++++++++ .OO......... ++++++++++",
"++++++++ .OO......              ",
"++++++++ .OO...... oooooooooooo ",
"         .OO...... oooooooooooo ",
" XXXXXXX .OO...... oOOooooooooo ",
" XXXXXXX .OO...... oOOooooooooo ",
" XOOXXXX ......... oOOooooooooo ",
" XOOXXXX ......... oOOooooooooo ",
" XOOXXXX           oOOooooooooo ",
" XOOXXXXXXXXX ++++ oOOooooooooo ",
" XOOXXXXXXXXX ++++ oOOooooooooo ",
" XOOXXXXXXXXX ++++ oOOooooooooo ",
" XOOXXXXXXXXX ++++ oooooooooooo ",
" XOOXXXXXXXXX ++++ oooooooooooo ",
" XXXXXXXXXXXX ++++              ",
" XXXXXXXXXXXX ++++++++++++++++++",
"              ++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++"
};
static const char *exit_icon[] = {
/* columns rows colors chars-per-pixel */
"43 43 202 2 ",
"   c #8C6B9D",
".  c #8C6C9E",
"X  c #8D6D9F",
"o  c #8D6E9E",
"O  c #8D6E9F",
"+  c #8E6E9F",
"@  c #8F6FA0",
"#  c #8D70A0",
"$  c #8E70A0",
"%  c #8F70A0",
"&  c #8E71A1",
"*  c #8F71A1",
"=  c #8F72A2",
"-  c #8F73A2",
";  c #8F73A3",
":  c #9071A0",
">  c #9171A1",
",  c #9173A2",
"<  c #9174A2",
"1  c #9074A3",
"2  c #9374A2",
"3  c #9375A2",
"4  c #9074A4",
"5  c #9075A4",
"6  c #9175A4",
"7  c #927BA7",
"8  c #937BA8",
"9  c #957FAB",
"0  c #9581AC",
"q  c #9582AC",
"w  c #9783AD",
"e  c #9784AE",
"r  c #9F83A9",
"t  c #9882AD",
"y  c #9883AF",
"u  c #9987B0",
"i  c #9987B1",
"p  c #9A86B0",
"a  c #9A88B1",
"s  c #9A89B1",
"d  c #9C8BB2",
"f  c #9D8CB2",
"g  c #9C8BB4",
"h  c #9D8DB5",
"j  c #9D8EB4",
"k  c #9E90B8",
"l  c #9D96B9",
"z  c #9E99BB",
"x  c #9E9ABC",
"c  c #9F9BBC",
"v  c #9F9CBD",
"b  c #A58EAB",
"n  c #AA94AE",
"m  c #AB94AF",
"M  c #AB95AF",
"N  c #AC94B0",
"B  c #A092B9",
"V  c #A29BBE",
"C  c #A09EBF",
"Z  c #A59CBD",
"A  c #BEA9BA",
"S  c #BFAABA",
"D  c #C0ABBA",
"F  c #C1ADBB",
"G  c #C5B2BE",
"H  c #A39EC0",
"J  c #A69EC1",
"K  c #A69FC1",
"L  c #A99FC1",
"P  c #A3A2C2",
"I  c #A6A2C3",
"U  c #A3A5C3",
"Y  c #A4A5C3",
"T  c #A7A5C5",
"R  c #A4A6C4",
"E  c #A9A2C3",
"W  c #ACA7C7",
"Q  c #AEA7C7",
"!  c #A5A8C5",
"~  c #A5A9C6",
"^  c #ABA7C9",
"/  c #A6ABC8",
"(  c #AFABC9",
")  c #ACAACA",
"_  c #A8AFCA",
"`  c #AFADCE",
"'  c #A9B1CB",
"]  c #A9B1CC",
"[  c #A9B2CC",
"{  c #AAB3CD",
"}  c #ABB5CF",
"|  c #ABB6CF",
" . c #B0B0CF",
".. c #ACB7D0",
"X. c #AEB8D2",
"o. c #B1B7D3",
"O. c #B3B7D2",
"+. c #B5B7D5",
"@. c #B2B9D3",
"#. c #B2B9D5",
"$. c #B4BCD7",
"%. c #B8BEDA",
"&. c #B9BFDB",
"*. c #CCBAC2",
"=. c #B7C1DB",
"-. c #B7C2DC",
";. c #BAC0DB",
":. c #BAC1DD",
">. c #B8C3DD",
",. c #BBC2DE",
"<. c #BCC3DD",
"1. c #BDC3DD",
"2. c #BFC5DE",
"3. c #BDC6E1",
"4. c #BEC6E1",
"5. c #BEC7E2",
"6. c #BFC8E2",
"7. c #BFC9E3",
"8. c #BFC9E4",
"9. c #BFCAE4",
"0. c #C0C6DE",
"q. c #C1C6DE",
"w. c #E9DCD4",
"e. c #EADCD4",
"r. c #EBDDD4",
"t. c #EBDED4",
"y. c #EBDED5",
"u. c #ECDFD4",
"i. c #ECDFD5",
"p. c #ECE0D5",
"a. c #F3E6D9",
"s. c #F3E7D9",
"d. c #F5E8DA",
"f. c #F9EDDC",
"g. c #F9EDDD",
"h. c #FAEFDD",
"j. c #C2C7E0",
"k. c #C2C9E0",
"l. c #C3C9E0",
"z. c #C0CAE0",
"x. c #C3CAE1",
"c. c #C0C9E2",
"v. c #C1CAE3",
"b. c #C2CBE3",
"n. c #C0CBE5",
"m. c #C1CBE5",
"M. c #C1CCE6",
"N. c #C2CCE6",
"B. c #C2CDE6",
"V. c #C3CEE7",
"C. c #C6CEE4",
"Z. c #C6CFE5",
"A. c #C4CEE7",
"S. c #C4CFE8",
"D. c #C7D0E6",
"F. c #C8D0E6",
"G. c #C8D1E6",
"H. c #C8D1E7",
"J. c #C9D1E7",
"K. c #C5D0E8",
"L. c #C6D0E8",
"P. c #C6D1E8",
"I. c #C7D1E8",
"U. c #C7D1E9",
"Y. c #C7D2E9",
"T. c #C8D2E8",
"R. c #CAD3E8",
"E. c #CAD4E9",
"W. c #CBD4E9",
"Q. c #C9D4EA",
"!. c #CAD5EA",
"~. c #CBD6EB",
"^. c #CCD5E9",
"/. c #CCD6EB",
"(. c #CCD7EB",
"). c #CFD7EA",
"_. c #CCD7EC",
"`. c #CDD7EC",
"'. c #CDD8EC",
"]. c #CED8EC",
"[. c #CED9EC",
"{. c #CFD9EC",
"}. c #CFDAEE",
"|. c #D0D8EA",
" X c #D1D9EB",
".X c #D2D9EB",
"XX c #D1DAEB",
"oX c #D1DBEE",
"OX c #D7DEED",
"+X c #D6DFEF",
"@X c #DBE2EF",
"#X c #DCE2EF",
"$X c #DAE2F0",
"%X c #DBE2F0",
"&X c #E2E6F1",
"*X c #E3E7F1",
"=X c #E1E6F2",
"-X c #E4E8F1",
";X c #E6EAF2",
":X c #E9EDF3",
">X c #EBEFF4",
",X c None",
/* pixels */
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X% % ; % % % % % % % ; % % ; % ; % % % % % % % ; % % ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. 7 / [ [ ' ' ' ' ' ' ' ' ' ' [ [ [ ' ' ' ' ' ' ' U # ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. q X.x ~ X.R x | ' x [ | v U ..~ x | | l _ | v P @.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u 3.9 I -.H q -.#.% o.-.e V ,.R 7 =.$.; @.l.j Z T.2 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u 8.h ` M.) k 8.,.y ,.n.B ^ M. .g 8.6.y q.^.E W Y.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.6.8.M.6.3.M.M.3.8.M.3.8.M.8.6.M.Y.T.Q.'.Q.^.T.2 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.Y._._.'.'.'.(.Y.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.M.M.M.M.M.M.M.M.M.M.M.M.M.M.T.'._.oX'.'.'.'.H.2 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.M.M.M.M.M.M.M.M.M.M.M.M.M.Y._.'.$X-XoX'.'.'.T.2 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.M.M.M.M.A.M.M.M.M.M.M.M.T.'.'.'.oX+X(.'.'.Q.6.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. u n.M.M.M..XOXA.M.M.M.M.M.Y.'.'.'.'.'.'.(.'.Q.M.6.2 ,X,X,X",
",X,X,X,X,X,X,X@ % ,X,X,X,X. u n.M.M.Q.&X;XXXM.M.M.M.Y._.'.'.'.'.'.'.'.Q.S.M.l.; ,X,X,X",
",X,X,X,X,X,X> S G 2 ,X,X,X. u n.M.M.M.^..XM.M.M.M.Q._.'.'.'.'.'.'.'.'.V.M.S.A.7 ,X,X,X",
",X,X,X,X,X> S s.d.D . ,X,X. u M.M.M.M.M.M.M.M.M.Q.(.'.'.'.'.'.'.'.Y.V.V.S.'.T.2 ,X,X,X",
",X,X,X,X> F s.h.t.N . ,X,X. u 9.M.M.M.M.M.b.M.T.(.(.'.'.'.'.'.'.'.V.9.S.'._.T.5 ,X,X,X",
",X,X,X> D s.h.t.m @ ,X,X,X. e %.%.;.;.;.%.;.1.q.x.k.k.k.b.T.'.Q.S.V.V.Y.'.'.T.; ,X,X,X",
",X,X> F s.h.h.*.2 % : : : > > > 2 ; 2 > < < < < 2 2 2 2 : ( Q.V.9.V.'.'.'.'.6.; ,X,X,X",
",X> D s.h.h.h.s.p.p.u.u.u.u.u.u.t.p.p.p.t.p.p.p.t.p.t.t.b E S.M.V.'.'.'._.Y.6.; ,X,X,X",
"  r u.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.f.h.f.h.f.h.h.h.h.n Z M.S.'.'.'.'.S.9.3.2 ,X,X,X",
",X> D s.h.h.h.s.p.t.u.u.u.u.u.u.t.p.t.p.p.p.t.p.p.u.p.t.b I S.'.'.'._.S.9.V.9.; ,X,X,X",
",X,X> F s.h.h.*.2 : : > : : : > 2 ; 2 2 < < < < 2 2 % 2 % W Q.'.'.'.S.V.9.Y.T.; ,X,X,X",
",X,X,X> D s.h.t.n @ ,X,X,X. q ,.q.x.x.x.x.x.k.k.k.2.;.;.<.H.'.'._.S.M.9.Y._.T.2 ,X,X,X",
",X,X,X,X> F s.h.t.N . ,X,X. a Y.(.(.(.'.(.'.(.(.Q.M.M.S.Q.'.'.(.Y.9.M.Y._._.b.; ,X,X,X",
",X,X,X,X,X> S s.d.S . ,X,X. f _.'.'.'.'.(.'.'.'.V.9.S.Q.'.'.(.Y.9.V.T.'.'.Y.6.; ,X,X,X",
",X,X,X,X,X,X> A G 3 ,X,X,X. f ^.'.'.'.'.'.'.Q.M.M.T.'.'.'.Q.T.M.9.T.Q.'.T.9.3.; ,X,X,X",
",X,X,X,X,X,X,X> > ,X,X,X,X. f (.'.'.'.'.'.Q.V.M.S.Q.'.'.'.Y.9.M.T.(.(.T.M.M.6.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. f (.'.'.'.'.Q.S.M.Y.'.'.'.'.V.M.M.Y.(.(.Y.M.M.M.3.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. f (.'.'.'.^.M.M.V.Q.'.'.'.V.M.9.Y.'.(.XXM.M.M.M.3.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. f (.'.'.Q.S.M.V.'.'.'.'.Y.M.M.Y._.(.#X-XQ.M.M.M.6.6 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. f ^.(.Q.M.M.S.Q.'.'.'.Y.9.M.T.'.'.@X;X>X-XQ.M.M.6.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. f '.Q.Y.M.Y.'.'.'._.V.M.M.Y.'.'.V.T.@X;X(.V.M.M.3.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. d Q.M.M.Y.(.'.(.'.S.M.9.Y.'.'.V.M.M.H.XXA.M.M.M.6.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. a M.M.S.Q.'.'.'.T.8.M.T.'.Q.T.M.M.M.M.M.M.M.M.9.3.2 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. a M.Y.Q.'.'.Q.Y.M.8.Y.'.'.T.9.9.M.M.M.M.M.M.M.M.3.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. a M.Q.(.'.(.Y.M.M.Y.Q.'.T.M.M.M.M.9.M.M.M.9.M.M.3.6 ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X. t l.T.T.H.M.3.3.l.Y.T.M.6.3.6.6.3.6.2.3.3.6.6.6.#.; ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X# 2 6 6 2 ; ; ; 6 6 2 ; ; ; ; ; ; ; ; 2 ; ; ; ; % . ,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X",
",X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X"
};
static const char *bin_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 13 1 ",
"  c #5C6BBF",
". c #5B6BC0",
"X c #5C6AC0",
"o c #5C6BC0",
"O c #7986CB",
"+ c #9EA7D9",
"@ c #9FA7D9",
"# c #9FA7DA",
"$ c #9EA8D9",
"% c #9FA8D9",
"& c #9EA8DA",
"* c #9FA8DA",
"= c None",
/* pixels */
"================================================",
"================================================",
"================================================",
"================================================",
"================================================",
"================================================",
"==================.oooooooo.====================",
"=================ooooooooooo ===================",
"=================oo========oo===================",
"=================oo========oo===================",
"===========oooooooooooooooooooooooo=============",
"===========oooooooooooooooooooooooo=============",
"===========oooooooooooooooooooooooo=============",
"=========oooooooooooooooooooooooooooo===========",
"=========oooooooooooooooooooooooooooo===========",
"=========oooooooooooooooooooooooooooo===========",
"=========oooooooooooooooooooooooooooo===========",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========*****OO****OO****OO*****=============",
"===========#***********************=============",
"===========***********************#=============",
"============*********************#==============",
"=============******************#*===============",
"================================================",
"================================================",
"================================================",
"================================================",
"================================================",
"================================================"
};

static const char *img_file_icon[] = {
/* columns rows colors chars-per-pixel */
"48 48 135 2 ",
"   c #272931",
".  c #2D2F35",
"X  c #2F3036",
"o  c #323339",
"O  c #3A3B3E",
"+  c #3A3B40",
"@  c #1A686C",
"#  c #147174",
"$  c #2F6B6E",
"%  c #2A777A",
"&  c #3E7A7E",
"*  c #47474B",
"=  c #47484C",
"-  c #4B4B4D",
";  c #575758",
":  c #5B5C5C",
">  c #515153",
",  c #4C7A7C",
"<  c #517779",
"1  c #636462",
"2  c #6F6F6D",
"3  c #B9AE5D",
"4  c #8A8663",
"5  c #918D67",
"6  c #99946C",
"7  c #99977B",
"8  c #A19C71",
"9  c #ACA766",
"0  c #ACA86B",
"q  c #B2AB62",
"w  c #A6A375",
"e  c #ADA878",
"r  c #B4AF7D",
"t  c #C3B85B",
"y  c #D8C857",
"u  c #E8D758",
"i  c #EDDB59",
"p  c #F4E25B",
"a  c #F9E65C",
"s  c #617F85",
"d  c #0D8889",
"f  c #0F8183",
"g  c #079697",
"h  c #0E9293",
"j  c #069D9E",
"k  c #169495",
"l  c #1B9293",
"z  c #119899",
"x  c #2D8587",
"c  c #278889",
"v  c #2D898B",
"b  c #328586",
"n  c #378689",
"m  c #298E90",
"M  c #00A7A7",
"N  c #428688",
"B  c #51888C",
"V  c #5D8383",
"C  c #5E8D92",
"Z  c #718A88",
"A  c #758183",
"S  c #6F9399",
"D  c #77989E",
"F  c #759DA2",
"G  c #78A0A5",
"H  c #7FA6AB",
"J  c #8B8B81",
"K  c #919A82",
"L  c #969F9A",
"P  c #9B9A94",
"I  c #96A086",
"U  c #95A28C",
"Y  c #8EA398",
"T  c #92A69A",
"R  c #B6B38D",
"E  c #BAB68D",
"W  c #A4A49D",
"Q  c #B6B49E",
"!  c #8FA2A4",
"~  c #83AAAF",
"^  c #90A3A6",
"/  c #92AFAD",
"(  c #90AAA3",
")  c #89AFB5",
"_  c #8EB5BA",
"`  c #94B6B9",
"'  c #ABABA5",
"]  c #AEAEA8",
"[  c #AAB1AD",
"{  c #B3B2A4",
"}  c #B3B3AB",
"|  c #B5B7B0",
" . c #BDBCB4",
".. c #C4BF8D",
"X. c #C0BFB7",
"o. c #E4DD9B",
"O. c #EBE39F",
"+. c #C0C0B7",
"@. c #C5C5BC",
"#. c #C7C8BF",
"$. c #CAC9BE",
"%. c #EEE7A1",
"&. c #F3EBA3",
"*. c #FEF6AA",
"=. c #96BDC2",
"-. c #99BEC2",
";. c #9AC0C6",
":. c #9CC3C8",
">. c #9EC8CD",
",. c #A1C9CC",
"<. c #A3CDD2",
"1. c #A7D1D6",
"2. c #A8D3D8",
"3. c #ACD8DD",
"4. c #AFDCE1",
"5. c #B1DEE3",
"6. c #B3E1E6",
"7. c #C7C9C0",
"8. c #CBCBC1",
"9. c #D0CFC5",
"0. c #D1D1C7",
"q. c #D4D4CA",
"w. c #DBDACF",
"e. c #DEDED2",
"r. c #E0DFD4",
"t. c #E2E1D6",
"y. c #E4E4D8",
"u. c #EAE9DD",
"i. c #EFEFE2",
"p. c #F0EFE3",
"a. c #F2F1E4",
"s. c #F7F6E9",
"d. c #F8F7E9",
"f. c #FDFCEE",
"g. c None",
/* pixels */
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.o ; 1 1 1 1 1 1 1 1 1 1 1 1 1 1 : O g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.2 8.y.i.u.i.u.i.u.u.i.i.i.u.u.i.u.w.7 4 g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.: r.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.u.R %.5 g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.] f.f.a.$.| a.f.f.f.f.f.f.f.f.f.f.f.u.R *.%.6 g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.X @.f.a.| w.s.f.f.f.f.f.f.f.f.f.f.f.f.i.R *.*.&.6 g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.f.7.e.f.f.f.f.f.f.f.f.f.f.f.f.f.f.p.R *.*.*.&.8 g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.} d.f.f.f.f.f.f.f.f.f.f.f.f.f.f.a.R *.*.*.*.&.w g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.] f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.d.{ &.*.*.*.*.&.e g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.e...*.*.*.*.*.&.r g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.8.E o.&.&.&.&.O.w g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.u.$.} { { { } J X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f. .o g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.f.s.7.[ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ y.f.f.f.f.@.. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.f.| =.3.2.<.` -.2.3.2.2.2.2.2.2.2.2.<.! i.f.f.f. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.a.^ 6.6.1.I 3 q T 3.6.6.6.6.6.6.6.6.6.-.8.f.f.f.7.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.a.^ 6.5.U u a p y / 6.6.6.6.6.6.6.6.6.:.7.f.f.d.@.. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.a.^ 6.1.w a a a p K 5.6.6.6.6.6.6.6.6.:.7.d.7.f. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 6.3.w p a a i Y 5.6.6.6.6.6.6.6.6.:.7.d.} d.@.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 6.5.) t i i 9 :.6.6.6.6.2.;.6.6.6.:.8.d.q.f.X.. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.] f.a.^ 6.6.5.-.( ( ,.6.6.6.6.5.F & >.6.6.:.7.d.] f.X.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 6.6.6.5.5.6.6.6.6.6.6.=.c j C 3.6.:.7.d.' d. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 6.6.6.4.5.6.6.6.6.6.2.B M M k ~ 5.:.7.d.| d.@.. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 6.6.3.S _ 5.6.6.6.5.G z M M M n :.:.7.d.q.f.X.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.a.^ 5.4.F k N <.6.6.6.-.v M M M M M C ` 7.s.] d. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.a.^ 4.~ l M j C 3.6.2.B M M M M M M k s 7.s.] d.@.. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.a.! ) v M M M k H 5.G z M M M M M M M % +.s.' d.@.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' d.a.s v M M M M M v F v M M M M M M M M h  .s.' d. .X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' f.u.< M M M M M M g @ M M M M M M M M M z  .s.' d.X.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.i., M M M M M M # g M M M M M M M M M z  .s.' d.@.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.u., M M M M M d # M M M M M M M M M M h  .s.' d.+.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.s.' f.a.Z M M M M j # M M M M M M M M M M M c 7.s.' f. .. g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.d.' d.f.8.V n b x $ $ x v x x x x x x x x N L s.s.] d.@.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.o @.f. .i.f.f.a.q.q.q.0.q.0.q.0.0.q.0.0.0.q.0.e.d.f.u. .f.X.X g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.X @.f.y.} p.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.a.} u.f. .  g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.W f.f.y.}  . . . . . . . . . . . . . . . . . . .} y.f.d.P g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.> q.f.f.d.i.u.y.u.u.u.u.u.u.u.y.u.u.y.u.u.u.u.a.d.f.f.9.- g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.: | r.y.y.y.y.y.y.t.y.y.y.y.y.y.y.y.y.y.y.y.y.y.e.} ; g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.  O = = = = = = = = = = = = = = = = = * * = * O   g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.",
"g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g."
};


static const char *folder_icon[] = {
/* columns rows colors chars-per-pixel */
"40 40 67 1 ",
"  c #4788C7",
". c #4B8DC8",
"X c #508FCB",
"o c #508FCC",
"O c #5391CC",
"+ c #5593CD",
"@ c #5692CD",
"# c #5693CD",
"$ c #5793CD",
"% c #5795D0",
"& c #5E98D0",
"* c #629AD2",
"= c #669ED3",
"- c #609BD4",
"; c #629CD4",
": c #649ED5",
"> c #679FD6",
", c #67A0D7",
"< c #68A1D6",
"1 c #6DA2D5",
"2 c #67A2DB",
"3 c #6BA3D8",
"4 c #6BA6DE",
"5 c #70A5D6",
"6 c #73A6D8",
"7 c #70A6DB",
"8 c #74AADD",
"9 c #79AADA",
"0 c #7AAEE0",
"q c #7FB2E3",
"w c #80AFDC",
"e c #87B4DF",
"r c #8CB8E1",
"t c #90BAE2",
"y c #90BBE2",
"u c #91BCE2",
"i c #93BCE2",
"p c #91C0EB",
"a c #90C6F7",
"s c #9CC8F1",
"d c #9DC9F1",
"f c #91C6F8",
"g c #97CCFD",
"h c #98CCFD",
"j c #B2D1EE",
"k c #B3D1EE",
"l c #B5D3EE",
"z c #A4CFF5",
"x c #ADD5F9",
"c c #BED9F2",
"v c #B2D8FC",
"b c #B4DAFD",
"n c #B4DBFD",
"m c #B5DBFD",
"M c #B5DCFE",
"N c #B6DCFE",
"B c #CFE5F8",
"V c #D3E7F9",
"C c #D6EAFB",
"Z c #D8ECFC",
"A c #DAECFC",
"S c #DAEDFC",
"D c #DCEDFD",
"F c #DDEFFD",
"G c #DEF0FE",
"H c #DFF0FE",
"J c None",
/* pixels */
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"J           .JJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"J NNNNNNNNNx+.JJJJJJJJJJJJJJJJJJJJJJJJJJ",
"J NNNNNNNNNNx+.JJJJJJJJJJJJJJJJJJJJJJJJJ",
"J NNNNNNNNNNNzX                        J",
"J NNNNNNNNNNpOrAHHHHHHHHHHHHHHHHHHHHHH J",
"J           &cHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHk++kHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHH+dd+HHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHH+ds$HHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHk++lHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHB5VHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHFV&2&VHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHC*wNq*CHHHHHuuHHHHHHHHHHHH J",
"J HHHHHHHHHA;qNNb0=AHHHu%%uHHHHHHHHHHH J",
"J HHHHHHHHA18NNNbN81AHu%ff%uHHHHHHHHHH J",
"J HHHHHHHF67bNNNNNN46r%fhhf%uHHHHHHHHH J",
"J HHHHHHF91bNNNNNNNb<ofhhhhf%uHHHHHHHH J",
"J HHHHHHw>bNNNNNNNNNb=2hhhhhf%uHHHHHHH J",
"J HHHHHe;vNNNNNNNNNNNb-4hhhhhf%uHHHHHH J",
"J HHHHr                         iHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH J",
"J                                      J",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ"
};
